### ISSUE TITLE
Model prompt release?

### ISSUE THREAD

**Issue by Ryosuke0104** [RocktimJyotiDas/EXAMS-V#1]
Thanks for your amazing work!!

Are there any plans to publish the prompts given to the VLM?

From the following figure in the paper, I think you are changing the prompt depending on the number of choice questions, but it is not included as metadata in the published data set and I cannot reproduce the prompt in full.

<img width="789" alt="image" src="https://github.com/user-attachments/assets/050f2de7-af23-4174-9061-e18775ed95fc">

**Comment by RocktimJyotiDas** [comment]
Hello @Ryosuke0104 ,

Thank you for your interest in our paper. We benchmarked our dataset using a single prompt, which I have included below. Please don't hesitate to reach out if you need any further assistance.

**Prompt:**

`"The image contains a multiple-choice question with 3 to 5 options. Provide the correct answer in JSON format as follows: `{'answer': 'xxx'}`. Replace 'xxx' with the appropriate letter: 'A' if the first choice is correct, 'B' if the second choice is correct, 'C' if the third choice is correct, 'D' if the fourth choice is correct, or 'E' if the fifth choice is correct."`
